---
title: "First Knit"
author: "Connor Rice"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas. For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation.

## A short history of you.

Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.

### my answer

Quartz hill High school, yes but barely. Math is easier for me but I get better grades in English, probably because I have to put in more effort in English courses.

## Your computer and your and its capability?

For this class you need a computer you can use at home. So, what kind is it (windows, Apple, Linux)? On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself? You also need to have have internet access. How is your connection to the internet where you live?

### my answer

I use a windows pc at home. I'd probably rate myself a 8-9 on the geek scale. The internet is fine where I live.

## Others and You?

What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be?

### my answer

I'm fine with being called anything that doesn't involve my last name.

## Aspirations?

What do you want to achieve in life? What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer

I want to go to med school and become a doctor. I enjoy chemistry a lot. By the time I transfer out of AVC I will have an associates in both Chemistry and Biology.

## Past adventures?

Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future? Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer

I have been to Morocco a few times to visit family. I have not been in the military, if I got drafted I would want it to be in the Navy. I have a few friends currently enlisted in the Navy and they have had good things to say about it.

## Why are you taking Statistics?

Did you take Math 115 or Math 116 ? Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??\
What grade do you need to attain in stats to not upset your future plans, What is your plan?

### my answer

I am taking math 116 because it is the one that is by far most commonly needed for transfer to the UC's I want to apply to. An A would be ideal to keep my GPA up. My future plans are to transfer to a good UC for premed then apply to NYU for medschool.
